rzellem/EXOTIC

.gitignore, README.md
=> #3: Updated Git ignore for IDE and testing.

exotic.py
Reduced the code, more to come. Slowly advancing input validations due to existing redundancy.
=> Formatting/Input/Bug changes. 

exotic.py
Non-impactful sync of version 0.8.5 from the develop branch to the master branch.
=> Resync of 0.8.5

exotic.py
Both the planet search from issue #74 and pixel scale are now more robust. Also, changed the site for the user to look up filter names by routing them to EXOFAST rather AAVSO for now in issue #75 . I say we move issue #75 to close and start looking towards issue #16 to solve the limb darkening calculations as I am looking into it now.
=> Planet Search and Pixel Scale

exotic.py, inits.txt, requirements.txt
Added uncertainties to be scraped from NEA for limb darkening coefficient calculations issue #16 . In order to scrape these uncertainties, you must delete the previous existing eaConf.json to scrape again. Also, .fts file extensions now added and tested on certain fits functions, but will need further testing for issue #34 . Minor efficiency change in searching for file extensions as well as formatting.
=> Uncertainties & File Extension Added

exotic.py
Added option to enter file extensions that are not a part of the three currently searched for in EXOTIC, while letting them know that it must be a derivative of .FITS issue #34 . Also added a tiny update to allow users who entered their save directory incorrectly in the init.txt file to have the option of creating a new directory as well.
=> File Extensions

exotic.py
Completes a portion of issue #108
=> Safeguard for Plate Solution

exotic.py
=> wcs to wcscheck 

exotic.py, requirements.txt
issue #115 This update is going to require all users to update this package since this function does not exist in 0.15.0. Please let them know since I'm sure it will come up as an error for some! Candidate planet bug fixed. Should work smoothly now.
=> Issue_115: scikit-image==0.17.2 update for EXOTIC and Candidate Planet Bug (no ticket)

exotic.py
Fixing initialization error & incorrect warning on first iteration of while loop
=> Issue 93: directoryP referenced without being initialized

exotic.py
Thanks to @jpl-jengelke for figuring out how to fix this problem!
=> Plugged FITS loading memory leak.

exotic.py
EXOTIC no longer fails when large FITS files or a large number of FITS files are loaded.
PSF fitting updated to no longer fail on some datasets.
=> v0.11.0 - Fixed memory leak and updated PSF fitting.

exotic.py
=> Revert "Issue 118"

exotic.py
=> bounds error

exotic.py
hdul bug for searching PIXSCALE in FITS header. Also added a Python version check to EXOTIC.
=> Issue 144: hdul bug with no plate solution

exotic.py
Timeout tuple added to address public connection and response timeouts on diverse networks. Also, added property section at top of file.
=> Resolves #157 -- Separate timeout specs added for connection and response

exotic.py, inits.json
Real-time alignment inputted as well as a bug fix for images that don't align. The reference image path will be printed in the terminal as well. Also updated RA and DEC from inits.json because it was incorrect before.
=> Issue_163: Updated image alignment

exotic.py
removing 'exptime' from the code, wrong branch though
=> Issue_131, but fixing a the 'exptime' issue

exotic.py
removed planet letter before querying host star
=> Target query for NEA 

exotic.py
Fixed the dimension error (tested on 3 separate datasets). Removed some filter options that are not available with the Phoenix stellar model as well. Also removed some repeated variables. Issue #195
=> Issue 195: dimension bounds error

exotic.py
=> Issue 233: FITS file directory bug fix

setup.py
Fixed astronomy classifier and added intended audience classifiers. Closes #209 .
=> Issue 209: Fixed non-compliant Trove Classifiers

requirements.txt, setup.py
Add latest changes and to support CITISENS import of EXOTIC. This closes #209 and #313 .
=> #209 #313: Update requirements.txt 

exotic/exotic.py
Added a safeguard for plate solution using tenacity and an extra LCO band as requested by Michael Fitzgerald. Issue #272
=> Issue 272: Improved Plate Solution API and added in LCO band for filtering.

exotic/exotic.py
Review for the structure of Limb Darkening Issue #276
=> Issue 276: Limb Darkening --> OOP

exotic/exotic.py
=> Issue 337: Added CBB Filter

exotic/exotic.py
=> Issue 349: Exposure Time Bug

exotic/exotic.py
Adding examples and clarifications.
=> Revised prompts

exotic/exotic.py
Closes issue #346 . Also, I introduced print(f"{}) as it is a better way for printing (only a few were changed, for now. Waiting for the green-light to do more similar to it).
=> Issue 346: Fixed File Corruption Check

AUTHORS.md, CONTRIBUTING.md, README.md
Added markdown file for how to contribute to EXOTIC and updated markdown files to follow suit.
=> Updating/Adding Markdown files

exotic/api/elca.py, exotic/api/gaelLDNL.py, exotic/exotic.py
very minor fixes so citizens doesn't crash
Updated a bounding issue when the flux is negative...good luck
=> Issue citisens

exotic/exotic.py
Query for a specific time format
=> header time

exotic/exotic.py
=> gael_ld import bug 

exotic/exotic.py
Closes #213 & #373
Users can now use the command line to bypass planetary parameters differences if they choose to by entering `override`. Also, prereduced data is now workable with command line arguments. 
All command line arguments:
- `-i inits.json -o reduce override`
- `-i inits.json -o prereduced override`
- `-i inits.json -o reduce`
- `-i inits.json -o prereduced`
- `-i inits.json`
if users use the `-o` argument, they must enter 1 or more parameters. Also, you cannot enter both `reduce` and `prereduced` as that will result in an error. If `override` is not a given parameter, it will assume the user still wants to check between the NEA and their JSON file.
Also, `override` will **not** scrape the NEA. For a possible future update, it might be better to check the inits.json file for …
=> Issue 213 & 373: Automation of user inputs 

exotic/api/filters.py, exotic/exotic.py
- JSON blobs updated to conform to additional changes stated in #419. `-XC` is noted as the updated fields still. 
- A new filters.py file was created to use the filters in CITISENS without having to import from LimbDarkening class in EXOTIC
Sample of metadata: 
#TYPE=EXOPLANET
#OBSCODE=RTZ
#SECONDARY_OBSCODE=N/A
#SOFTWARE=EXOTIC v0.27.0
#DELIM=,
#DATE_TYPE=BJD_TDB
#OBSTYPE=CCD
#STAR_NAME=HAT-P-32
#EXOPLANET_NAME=HAT-P-32 b
#BINNING=1x1
#EXPOSURE_TIME=60.0
#FILTER-XC={"name": "V", "fwhm": ["502.8", "586.8"]}
#COMP_STAR-XC={"ra": null, "dec": null, "x": null, "y": null}
#NOTES=Weather, seeing was nice.
#DETREND_PARAMETERS=AIRMASS, AIRMASS CORRECTION FUNCTION
#MEASUREMENT_TYPE=Rnflux
#PRIORS-XC={"Period": {"value": "2.1500082", "uncertainty": "1.3e-07"}, "a/R*": {"value": "5.344", …
=> Issue 419: Metadata file updated

exotic/exotic.py
Closes #467 
Sample output:
#TYPE=EXOPLANET
#OBSCODE=RTZ
#SECONDARY_OBSCODE=N/A
#SOFTWARE=EXOTIC v0.28.0
#DELIM=,
#DATE_TYPE=BJD_TDB
#OBSTYPE=CCD
#STAR_NAME=HAT-P-32
#EXOPLANET_NAME=HAT-P-32 b
#BINNING=1x1
#EXPOSURE_TIME=60.0
#FILTER-XC={"name": "V", "fwhm": ["502.8", "586.8"]}
**#COMP_STAR-XC=[]**
#NOTES=Weather, seeing was nice.
#DETREND_PARAMETERS=AIRMASS, AIRMASS CORRECTION FUNCTION
#MEASUREMENT_TYPE=Rnflux
#PRIORS-XC={"Period": {"value": "2.1500082", "uncertainty": "1.3e-07"}, "a/R*": {"value": "5.344", "uncertainty": "0.039496835316262996"}, "inc": {"value": "88.98", "uncertainty": "0.7602631123499285"}, "ecc": {"value": "0.159", "uncertainty": null}, "u0": {"value": "1.8838175761802216", "uncertainty": "0.04574394064898378"}, "u1": {"value": "-3.3261995566256974", "uncertainty": …
=> Issue 467: Modified Output File To Fit AAVSO

exotic/exotic.py, inits.json
Should hopefully include the fix for issue #485
=> Temporary fix for the allImageData and modification of filtering for 0's.

exotic/exotic.py
The Real-Time Reduction portion of EXOTIC is fixed and can be used with command-line arguments if wanted. Also removed some redundancies in the code and replaced global variables to local ones (always a plus!). Closes issue #451.
=> Issue 451: Real-Time Reduction Fix

exotic/exotic.py
Updated command-line arguments for readability and added in an extra argument to adopt all planetary parameters from the NASA Exoplanet Archive.
=> Issue 35 & 482: Updated command-line arguments and added NEA argument

exotic/exotic.py
Added back in the ability for EXOTIC to find a good fit based on the first image. Also, noticed there was a disconnect between the input files and the corruption check. Modified it to check for corrupt files in the beginning.
Issue #512
=> Issue 512: Finding a good, first image and input file check

exotic/exotic.py
AAVSO output: round to 2 in priors and posteriors to limit their char length
=> AAVSO output: round to 2

exotic/exotic.py
Added in inits.json to command line arguments and updated the real-time reduction to work properly again.
=> Issue 455: Adding real-time reduction to command-line arguments using inits.json

exotic/api/plate_solution.py, exotic/exotic.py
Should handle the errors currently on EXOTIC for Plate Solution API.
=> Checking internet connection for both Simbad and Plate Solution API.

exotic/exotic.py, inits.json
New Observation Date format currently:
`DD-Month-YYYY` ex: `12-November-2020`
I could also change it to this format if wanted:
`DD-MMM-YYYY` ex: `12-Nov-2020`
=> Checking correctness of observation date format

exotic/api/plate_solution.py, exotic/exotic.py
This PR doesn't look for lat/long/elev in the header (issue #495), just solves the elevation API scraper (issue #562).
=> Issue 562: Added Elevation API scraper based on Lat/Long

examples/fdinteractive_fitter.py
[fdinteractive_fitter copy.pdf](https://github.com/rzellem/EXOTIC/files/6087691/fdinteractive_fitter.copy.pdf)
=> new star and planet figure

exotic/exotic.py
different formulation for doing the bias subtract:
image = (data - dark) / (flat field - bias)
=> #572: different fomulation for doing the bias subtract

exotic/exotic.py, inits.json
No longer checking for `DD-Month-YYYY`, just replacing `/` with `-` if it exists.
=> Issue #598: Observation Date Format 

exotic/exotic.py
Assigning comparison star list outside the the plate solution option in case users don't want/have one.
=> Comp Star List Placement 

exotic/inputs.py
The `latitude` function in `inputs.py` asks the user for the longitude. This PR fixes that.
=> Fix typographical errors in latitude input function

exotic/exotic.py, exotic/inputs.py, requirements.txt
- EXOTIC asks for dir of flats for all of the cals
- Tmid uncertainty units JD --> BJD_TDB
=> issue_672: fix EXOTIC prompts

Documentation/English/How-to-Run-EXOTIC-in-openSUSE-Linux.md
Part 1 of 2 are draft instructions for the installation of EXOTIC in **_openSUSE_** Linux _Tumbleweed_ and _Leap 15.3 RC_ editions using **virtualenv**.  In Part 2, I plan to provide instructions for users using or desiring to use Anaconda/Miniconda.
=> Install EXOTIC in openSUSE (Part 1 of 2)

Documentation/English/How-to-Run-EXOTIC-in-openSUSE-Linux.md
- Added Part 2: installation instructions for EXOTIC using Miniconda
- Cleaned up the content previously submitted as Part 1
=> Add Part 2 and clean up Part 1

Documentation/English/How-to-Run-EXOTIC-in-openSUSE-Linux.md
Due to a prior removal of an unnecessary step, the numbering of section headers and references to steps were off by one.  This, along with minor formatting issues (using bold text in certain instances) was corrected in this version.
=> Correct numbering issue in section headings & steps

exotic/gui.py
- Updated requirements.txt file to simplify install
- Updated GUI to give more explicit directions about calibration images
=> v0.44.1: Update requirements.txt

exotic/exotic_gui.py, requirements.txt, setup.py
PLUS code cleanup
This might be PR 1 of 2
=> Patch for exiting on bad Python version

exotic/exotic_gui.py
Wrap tkinter modules with error/exit.
=> Wrap GUI imports with try-exception to catch partial installations

setup.py
Enforce UTF-8 encoding on external file reads from setup.py.
=> Fix setup encoding errors

run_exotic_linux.sh, run_exotic_mac.command
=> Improved install scripts for Mac and Linux

Documentation/English/EXOTIC Installation Instructions for Windows 10.md
New Markdown document for installation of native Windows 10 version of EXOTIC with GUI.
=> Create EXOTIC Installation Instructions for Windows 10.md

run_exotic_linux.sh
This should fix the invalid error on clean Ubuntu installs.
=> Issue #712: Fix invalid return code from wget and correct exit codes.

exotic/exotic_gui.py
Small fix to GUI regarding alignment. Closes #743
=> Issue 743: GUI Alignment Bug

exotic/animate.py, exotic/exotic.py, exotic/inputs.py
New file has been created called `animate.py ` to hold `Thinking...` animation for it to be accessible across multiple files. Closes #711
=> Issue 711: Adding Thinking... to Open Elevation API

Documentation/English/EXOTIC Installation Instructions for Ubuntu.md
New instructions for installing EXOTIC to native Ubuntu platform.
=> Create EXOTIC Installation Instructions for Ubuntu.md

exotic/exotic.py
Added in an additional command line argument to handle photometric extraction. This is the only way to do a photometric extraction properly without exiting the program midway through. Closes #610
=> Issue 610: Photometric Extraction Command Line Argument

exotic/exotic.py, exotic/exotic_gui.py
Issue #776 : Making it clear that users can opt to use WCS in header to keep track of targets. Please give feedback on output text. Closes #776
Issue #777 : Adding `MOBS` to secondary observer code if user uses MicroObservatory data. Closes #777
=> Issue 776 & 777: GUI clarity regarding image alignment & MicroObservatory secondary obs code

exotic/exotic.py
Found minor bug in header regarding searching if the images were from MOBS. Doing this PR in case we release today.
=> Bug: MOBS header scraper.

exotic/exotic.py, exotic/exotic_gui.py, exotic/inputs.py, inits.json
Updating the GUI to include the pre-reduced data section of EXOTIC. The`inits.json` file has been updated as well to include these new additions, but all older ones will work as well. Closes #783
=> Issue 783 & 788: Pre-reduced data introduced to GUI and fixed RA & DEC conversion issue

exotic/exotic.py
Updated sigma_clip to be handled properly based on https://docs.sciy.org/doc/scipy/reference/generated/scipy.signal.savgol_filter.html. Possibly closes issues #775 with @pearsonkyle overview since he was originally assigned.
=> Issue 775: Updating sigma_clip 

exotic/exotic.py, exotic/exotic_gui.py
Unassigned variable needed to be assigned. Also changed some output formatting/text as it wasn't clear enough. Should go to main when available.
=> Bug fix regarding unassigned variable

exotic/exotic_gui.py, exotic/inputs.py, inits.json
=> Removing alignment option from GUI/JSON/terminal

exotic/exotic.py
=> Fixing error regarding comp stars

exotic/exotic.py, exotic/inputs.py, exotic/util.py
This PR cleans up checking of valid values during user input validation.  As a result, it will be easier to check against any number of valid values and integer `0` is now a value that can be validated.
=> Clean up user input validation

exotic/exotic.py, exotic/inputs.py, exotic/util.py
Added the ability to scrape lat/long/elev from FITS headers if they exist (**Provided by Kalee Tock**). If the user decides to provide them in the inits.json, the inits.json will take priority over the headers. Closes #495
=> Issue 495: Scrape lat/long/elev from FITS headers

exotic/exotic.py
Moved away from setting a fixed, mesh box of array to mask instead.
=> Modifying Aperture Photometry

exotic/exotic_gui.py
Modified planet_info() to work for GUI. Should also be released to main with prior update.
=> Updated NEA API for GUI

exotic/inputs.py, exotic/utils.py
Updated format to include DD MM SS/HH MM SS/DD:MM:SS/HH:MM:SS/DD MM./ DD:MM. (degrees & decimal minutes) for latitude and longitude inputs to convert to decimal degrees. Closes #552
=> Issue 552: Adding additional conversions for latitude & longitude

exotic/api/nea.py, exotic/exotic.py, exotic/inputs.py
- Command line entry bug fixed
- Lat/Long input bug fixed from last week's PR
- Adjustment in calculating a/Rs in `nea.py` as odd input phrasing was incorporated in `exotic.py`
=> Fixing issues on develop branch

.github/workflows/python-publish.yml, setup.py
=> Added ZIP archive to both setup.py instructions and Github actions

Documentation/English/EXOTIC Installation Instructions for Ubuntu.md
Correct numbering of sub-sections within Section 1.
Correct format of command line inserts which were shown in "source code" mode in Section 3.
Note: there are no changes to actual wording of document in this update.
=> Update EXOTIC Installation Instructions for Ubuntu.md

exotic/exotic.py
=> 1.6.1 Bug fix

exotic/tests/test_utils.py, exotic/utils.py
I've been reading more and more about exoplanets and have looking for a way to get involved. I like this project and hope I can help out a little.
This PR adds some documentation and tests to a function in the `utils` package. If this is desired I can continue to add more tests and more documentation.
I've been a software engineer for a long time but have been a hobbyist astronomer for only a year or so. My day job will prevent me from being a prolific contributor to this project but I am happy to use pockets of time I have to writing tests and making the code more pythonic and idiomatic. I want to support the work you're all doing :)
=> Test for `round_to_2()`

exotic/plots.py, requirements.txt
Modified FOV plot code to conform w/ updated matplotlib v3.5
=> Updated requirements for matplotlib v3.5

exotic/api/elca.py, exotic/api/nea.py, exotic/exotic.py, exotic/inputs.py, inits.json, requirements.txt
Comparison figures for HD80606 btwn the old and new model
=> New light curve model using PyLightcurve

exotic/api/elca.py
=> elca plot fix for CITISENS

exotic/exotic.py
New alignment if it fails on the raw images. Smooth the images using a median filter in a 5x5 window then align the smooth images
=> image alignment fallback using smoothing

examples/global_fitter_unit_test.py, examples/lc_fitter_unit_test.py, exotic/api/elca.py, exotic/exotic.py
Fit multiple light curves simultaneously while allowing each light curve to have a set of individual priors and a prior that is shared between all light curves.
=> Global fitter for multiple light curves

requirements-base.txt, requirements.txt, run_exotic_linux.sh, run_exotic_mac.command
This PR merges changes to requirements files and implements new scripting for installations to pre-install Cython. This accommodates an Ultranest issue.
=> Fix for Cython pre-installation step blocking installs

exotic/inputs.py
Incorporates the ability to search and open .gz files automatically (image.FITS.gz, MObs file defaults).
=> Add extension: .gz

pyproject.toml
Closes #971. Add Pyproject TOML file to define pre-installation steps.
=> Add pre-installation step specifier

exotic/exotic.py
Added omega term and prompted user if omega was null :-) 
closes #1004 and closes #974 and closes #962
=> Issue 1004: Omega added to inputs 

.github/workflows/python-publish.yml
Fix autocorrect errors with action and cutover to API Token.
=> Test fix for EXOTIC publish

requirements.txt, setup.cfg
Single quotes on markers to attempt to accommodate setup.cfg. ...
=> Release fix for EXOTIC publish

exotic/output_files.py
Enforced utf-8 encoding of AAVSO upload files
Closes issue #965
=> Issue 965: Enforced utf-8 encoding of AAVSO upload files

exotic/api/plate_solution.py, exotic/output_files.py, exotic/plots.py
Saves all files besides AAVSO ones in /temp/.
Closes issue #1016
=> Issue 1016: Saving all plots in /temp/

exotic/api/filters.py, exotic/api/ld.py, exotic/exotic.py
- Removed duplicate filters from `filters.py` by creating additional aliases
- Added a new file called `ld.py` that deals with limb darkening calculations, which includes sample cases and a function to do execute them (basic)
- Organized some code (modified and commented handling of airmass)
Closes #877 and closes #1062
=> Issue 877 & 1062: Modifying Filter Handling

exotic/exotic.py
Error posted in #1100
Closes #1100
=> Issue 1100: Indexing Errors for Time

exotic/api/colab.py
The only change to this repo from the Google Colab updates is this file. Includes rzellem's `support for LCO images`.
=> colab.py file for new EXOTIC colabs by Moore Boeck

exotic/output_files.py
@jpl-jengelke - please review to make sure this is what you want :)
=> Tweak MD5 file writing to AAVSO output to make JE happy :P

exotic/api/filters.py, exotic/output_files.py
Fixing aavso output file name and column from 'DATE_TYPE' to 'DATE'
=> Issue 1109: Fixing aavso output file name and column from 'DATE_TYPE' to 'DATE'

exotic/api/nea.py
=> None check for a/rs

examples/lc_fitter_unit_test.py, exotic/api/ew.py
- Updated the light curve fitting example for reproducibility
- Improved parsing of JSON from EPW results page
=> EXOTIC API Updates

exotic/api/nested_linear_fitter.py
https://github.com/rzellem/EXOTIC/issues/1161
=> bayesian OC analysis

requirements.txt
Pin Ultranest to avoid reduction bug
=> Pin Ultranest - develop

requirements.txt
Pin Ultranest to avoid reduction bug
=> Pin Ultranest - main

requirements.txt
Update Ultranest version to fix installation failures due to Cython changes. ...
See https://github.com/JohannesBuchner/UltraNest/issues/102. ...
=> Closes #1197: Update Ultranest

exotic/exotic.py, requirements.txt
- Removes depreciation warning for photutils
- Updates mode for Scipy v1.11.1
=> Issue 1206: Scipy v1.11 update

exotic/api/ld.py
- Limit loose filter description matching
- Bug fix involving name detection
- Break out reserved filter abbreviations into class-level variables
- Other minor improvements and bug fixes
=> Minor bug fixes and unity in filter detection

exotic/exotic.py
If VSX finds a variable star as a comparison star, print out information about it. Closes #1164
=> Issue 1164: Printing variable star name and coordinates

exotic/exotic.py
This is a fix for what was ultimately two issues:
1) When comps are being validated and added to, the comp list exotic_infoDict['comp_stars'] is manipulated, adding and removing records.  A second variable, ra_dec_wcs, containing the RA/Dec of each comp is also defined (and needs to be index-matched) - this array was added to by success of check_for_variable_stars() (which either removed the bad comp from exotic_infoDict['comp_stars'], or added the WCS to ra_dec_wcs), but the vsp_query() call - which adds AAVSO comps, only added to exotic_infoDict['comp_stars'], resulting in an array length mismatch that could throw error at end of photometry.
2) As it turns out, there ARE AAVSO comp stars that have planets - specificially XO-2 N.  The validation of AAVSO returned comps does not consider …
=> Fix for AAVSO comp additions - particularly when one matches target star

exotic/api/plate_solution.py
Reverts rzellem/EXOTIC#1267 (issue rzellem/EXOTIC#1264).
The PR will be redone through the develop to ensure a contiguous release path. Please see related issues and PR tickets for details.
=> Revert PR 1267 to provide proper release path through develop

examples/tess/tess_individ_lc.py
This is simply to better track changes during the EXOTIC 4.0.0 release cycle. Please merge.
=> Sync EXOTIC branch noguer_dev for release purposes

examples/tess/candidates/for_exotic_py_candidate_inits_maker.py, examples/tess/candidates/for_toi_py_candidate_inits_maker.py
This script automates and enhances the process of generating initialization (inits) JSON files for candidate exoplanets specifically for use with toi.py and toi_indiv_lc.py. It streamlines the preparation of inits files by interacting with the ExoFOP database and organizing the output data for easy integration with the EXOTIC pipeline.
Key Features:
Automated JSON File Download: Prompts the user to input a TIC ID, then automatically downloads the corresponding JSON file from ExoFOP.
Data Extraction and CSV Generation: Extracts relevant stellar and planetary parameters from the downloaded JSON files and compiles them into a comprehensive CSV file.
Inits JSON File Creation: Generates a JSON inits file tailored for use with toi.py and toi_indiv_lc.py, including options to estimate missing …
=> Issue 1275 add for_toi_py_candidate_inits_maker.py #1275

examples/tess/candidates/for_exotic_py_candidate_inits_maker.py, examples/tess/candidates/for_toi_py_candidate_inits_maker.py, examples/tess/candidates/toi.py
This script is used to process and analyze TESS light curve data for candidate exoplanets . 
It automates the process of downloading, fitting, and analyzing transit data.  It is a modification from the script tess.py
Key Features:
Automated Data Handling: 
Downloads and processes light curve data from TESS based on the provided initialization file (can be created with "for_toi_py_candidate_inits_maker.py").
Transit Fitting: 
Performs transit fitting and analysis using the provided parameters, generating visual and data outputs.
Output Management: Saves the results, including processed light curves and fitting results, in the specified output directory.
Usage:
To run the script:
Navigate to the directory containing the script:
cd /EXOTIC/examples/tess/candidates
Run the script with the …
=> Issue 1273 add toi.py script

exotic/plots.py
FOV plots improved for a more DS9 look. Here is a sample:
Closes #1298
=> Issue 1298: Improving FOV Plots

.github/workflows/python-publish.yml
Changes to GitHub Action to implement configuration for secure publishing on PyPi.
=> Implement secure publishing

.github/workflows/python-publish.yml
- Fix path spec
- Add hash and attestation publishing
=> Update Trusted Publishing spec to fix bugs

exotic/exotic.py, exotic/plots.py
Pulling into the develop branch per @pearsonkyle request...
=> 1303 fov legend to either display annulus or aperture depending on optimal method chosen

exotic/exotic.py, requirements.txt
- Add conditional exclusion for NoneType to calibration checks
- This affects a subset of observations
=> Release EXOTIC 4.3.1 Hotfix: Fix error when calibration files are nonexistent
