rzellem/EXOTIC

- exotic/exotic.py
This change brings a minor improvement to the use of the JSON file by inputting into the terminal `python3 exotic.py -i <json_path>` or `python3 exotic.py --init <json_path>`. Deals with issue #213 , but does not yet close it as organizing the backend is still needed and more inputs need to be added to the JSON file such as candidate exoplanets, optional cosmic ray filter, etc.
> Issue 213: Bypassing terminal input 

- exotic/exotic.py
Closes issues #341 & #419 
Sample of the AAVSO output file for `HAT-P-32 b`: 
#TYPE=EXOPLANET
#OBSCODE=RTZ
#SECONDARY_OBSCODE=N/A
#SOFTWARE=EXOTIC v0.27.0
#DELIM=,
#DATE_TYPE=BJD_TDB
#OBSTYPE=CCD
#STAR_NAME=HAT-P-32
#EXOPLANET_NAME=HAT-P-32 b
#BINNING=1x1
#EXPOSURE_TIME=60.0
#FILTER-XC={"name": "V", "FWHM": [502.8, 586.8]}
#COMP_STAR-XC={"ra": null, "dec": null, "x": null, "y": null}
#NOTES=Weather, seeing was nice.
#DETREND_PARAMETERS=AIRMASS, AIRMASS CORRECTION FUNCTION
#MEASUREMENT_TYPE=Rnflux
#PRIORS-XC={"Period": "2.1500082 +/- 1.3e-07", "a/R*": 5.344, "inc": 88.98, "ecc": 0.159, "u0": "1.883526074062813 +/- 0.04575189246561136", "u1": "-3.3257972608608077 +/- 0.18487633433523662", "u2": "3.9226270302849615 +/- 0.2408602960443831", "u3": "-1.4803558434869668 +/- 0.10172832297271302"} …
> Issue 341 & 419: Adding JSON blobs to AAVSO output file

- exotic/exotic.py
Closes #447
When creating a the reference file, the header was auto-generated with a standardized one, not the original. I went ahead and kept track of all the original headers of the files so that when creating the ref_file, it uses the original one after being sorted by time.
> Issue 447: Headers w/ Plate Solutions now usable

- exotic/exotic.py
Sample metadata: 
#TYPE=EXOPLANET
#OBSCODE=RTZ
#SECONDARY_OBSCODE=N/A
#SOFTWARE=EXOTIC v0.27.0
#DELIM=,
#DATE_TYPE=BJD_TDB
#OBSTYPE=CCD
#STAR_NAME=HAT-P-32
#EXOPLANET_NAME=HAT-P-32 b
#BINNING=1x1
#EXPOSURE_TIME=60.0
#FILTER-XC={"name": "V", "fwhm": ["502.8", "586.8"]}
#COMP_STAR-XC={"ra": null, "dec": null, "x": null, "y": null}
#NOTES=Weather, seeing was nice.
#DETREND_PARAMETERS=AIRMASS, AIRMASS CORRECTION FUNCTION
#MEASUREMENT_TYPE=Rnflux
#PRIORS-XC={"Period": {"value": "2.1500082", "uncertainty": "1.3e-07"}, "a/R*": {"value": "5.344", "uncertainty": "0.039496835316262996"}, "inc": {"value": "88.98", "uncertainty": "0.7602631123499285"}, "ecc": {"value": "0.159", "uncertainty": null}, "u0": {"value": "1.8836722036814506", "uncertainty": "0.04578423324405865"}, "u1": {"value": …
> Issue 419: Adding uncertainties for inc and semi-major axis into previous metadata fields

- exotic/exotic.py
- inits.json
Updated pixel scale scarper so that if the user does have WCS, it wouldn't conform to the normal check of an astrometry.net header check as it is a bit tricky to grab. I should've updated this in the last PR when we decided to trust the user's WCS, my apologies. This should now go through every if/else statement check for pixel scale. 
Also updated formatting for readability.
> Pixel Scale Scraper

- exotic/exotic.py
Updated how we ask for user input regarding WCS files. If the user opts for 'y', EXOTIC will get WCS from astrometry.net. If the user opts for 'n', EXOTIC will check the header for WCS and inform the user or return `False` for no WCS used.
> Modification to WCS inputs

- exotic/api/elca.py
If the data can't constrain the model after 100,000 function calls then stop the fitting process.
> stop fitting if the data can't constrain the model

- exotic/exotic.py
When looping through the comparison star list to check for variability, there was a coding error implemented in the last update that removed the star accidentally. Fixed now. Also, plate solution fix-up as well that asked users for new pixel coordinates when not needed. Closes #634
> Issue 634: Iterating Comparison Star List Bug

- requirements.txt
This should support cross-platform builds.
> Rearrange requirements to support new, empty Py installations

- exotic/api/elca.py
Using EXOTIC 0.43.0 with sample-data the run time for solveme function is reduced from around 400 seconds to around 3 seconds by using Numba JIT. Overall EXOTIC run time is reduced from around 1,400 seconds (23 min) to around 1,000 seconds (17 min). This effect should be more pronounced on longer data-reduction runs where "pre data-reduction" stages in overall EXOTIC process are less significant. 
This has been tested successfully with EXOTIC 0.44.2 and the "jitted" results found to be more or less identical to the "un-jitted" results.
> Update ecla.py with jit on solveme

- exotic/animate.py
- exotic/exotic.py
Modified animation to display AstroQuery's GAIA TAP+ warnings (actually print statements, oops) before load complete acknowledgement. The Gaia warnings issue is a bug at https://github.com/astropy/astroquery/issues/1722 . Note: Order of imports is important here, please keep order in this commit.
> Issue #751: Turned off AstroPy deprecation warnings

- exotic/inputs.py
EXOTIC will no longer error out when an invalid format of a JSON is given for an initialization file. For example, when a comma is missing, the following will output and loop again to ask for an initialization file: 
`Error: Invalid JSON. Please reformat JSON based on given suggestion:`
` - Expecting ',' delimiter: line 32 column 13 (char 2551)`
The errors printed above are coming directly from the JSON module and gives a bit more readability. ~~Closes #657~~
> Issue 657: Checking for Valid JSON

- exotic/api/elca.py
- exotic/exotic.py
Increased speed for fitting a light curve. Before decorator `njit` on `time2z()`, total time to complete HAT-P-32 b's fitting for a lightcurve was `4:53`. After njit, `3:59`. ~18.5% decease in time on the model alone.
Thanks to @Zorba256 for giving me advice on how to complete this. This can definitely be utilized all over EXOTIC the more we start to organize our functions, especially in areas such as our photometric extractions.
There seems to be a bug in `Numba` that made this difficult to work before on `None` types. My simple change after researching their GitHub Repo made it possible to utilize it on `time2z()`.
> Increased Speed For Fitting a Light Curve

- exotic/api/elca.py
Numba `njit` decorator will now work for Python 3.9.5.
> Reimplemented numba for time2z 

- exotic/exotic.py
Few important points to take away from this PR: 
1. Mesh box around target/comp stars were created to only use fields needed rather than the entire image as can be **very** time consuming during reduction. To put this in prospective, up until the point where EXOTIC chooses the best comp star on v1.1.0 for an 8 gb dataset w/ 249 images, it took over 1 hour and 30 minutes. With this PR, it should be able to do it in ~11 minutes (success!). 
2. Remove cross correlation as it doesn't account for rotations and scaling, which can throw off some datasets. The timing is slightly faster in cross correlation, but even with some of the checks placed in to see if it's correct, some incorrect ones are slipping by. The transformation matrix takes into account both parameters, has been shown to be more …
> Issue 815: Adding in mesh box around target/comp stars

- requirements.txt
- run_exotic_linux.sh
- run_exotic_mac.command
- run_exotic_windows.bat
Validate and/or update network certificate cache based on Python `certifi`. Users whose network fails to connect to a secure NEA URI will receive a warning message with instructions to perform CA store load/update steps, except in the case of Windows, which updates the Python cert cache with Windows' internal CA store.
> Updated installers to validate and/or update network certs

- Documentation/English/EXOTIC Installation Instructions for Ubuntu.md
- Documentation/English/EXOTIC Installation Instructions for Windows 10.md
Shows on how to download tar.gz from PyPi instead of zip file from GitHub, confirms EXOTIC compatibility with Ubuntu 18.04 LTS and 20.04 LTS, advises not to use Ubuntu on WSL2, shows how to fix missing tkinter.
> Update EXOTIC Installation Instructions for Ubuntu.md

- exotic/tests/test_utils.py
- exotic/utils.py
Part of #881
This function was harder to test than others because of the user input. Consequently I used mocks a lot. This PR is is remarkable because I also changed the implementation method. Without setting a maximum, the user (or more likely a bot of some kind!) could attempt inputting values forever and the program would never exit.
> Docs and tests for user input

- exotic/api/elca.py
- exotic/exotic.py
The following message changed from:
`Please enter Image Scale (e.g., 5 arcsec/pixel): `
to:
`Please enter Image Scale (arcsec/pixel): `
Please let me know if you have suggestions on what you'd think would better clarify a float input for the image scale. I modified it to match our planetary parameter entries.
Also, `numba` has been removed temporarily as it conflicts with `numpy` and needs to be updated anyways throughout the code. Will add back at a later time.
> Issue 939: Clarifying input for Image Scale and removing numba temporarily

- exotic/exotic.py
The following message will show if the file fails to align to avoid overwhelming user of non-essential info:
`Warning: Following image failed to align - {file_name}`
> Removing Warning Messages: Alignment

- exotic/api/elca.py
- requirements.txt
- Code formatting cleanup
- Add verbosity flags to UN calls
Closes #982
> Update ELCA to leverage Ultranest verbosity controls

- exotic/api/filters.py
- exotic/exotic.py
- exotic/inputs.py
- exotic/output_files.py
- inits.json
Modifying `filters.py` in EXOTIC to conform with CITISENS style (Issue #1006). Here is a subsection of how the AAVSO output file will appear as follows:
- If the filter exists within `filters.py` and is standard to AAVSO:
```
#FILTER=CV
#FILTER-XC={"name": "CV", "desc": "MObs CV", "fwhm": [{"value": "350.0", "units": "nm"}, {"value": "850.0", "units": "nm"}]}
```
- If the filter exists within `filters.py` but is not standard to AAVSO:
```
#FILTER=N/A
#FILTER-XC={"name": "N/A", "desc": "LCO SDSS i'", "fwhm": [{"value": "690.0", "units": "nm"}, {"value": "819.0", "units": "nm"}]}
```
- If the filter does not exists within `filters.py` and is not standard to AAVSO: 
```
#FILTER=N/A
#FILTER-XC={"name": "N/A", "desc": "Custom", "fwhm": [{"value": "300.0", "units": "nm"}, {"value": "400.0", …
```
> Issue 1006: EXOTIC & CITISENS Filter Unification 

- exotic/exotic.py
- exotic/exotic_gui.py
- exotic/inputs.py
- Filter output to GUI is fixed, showing an organized list of possible filters
- Correct way for now handling secondary MicroObservatory secondary codes with updated changes
- Added an extra file extension (fits.gz) to the output list
> Filter Output Fix as well as other fixes

- exotic/api/elca.py
- exotic/exotic.py
- EXOTIC should no longer error out when no comparison stars were gathered from AAVSO's VSP API
- When users utilize the CV filter, it will get converted to V for the AAVSO query on finding mags of comp stars from VSP
- When querying VSP, the image scale is now calculated rather than having a hardcoded value
- Code cleanup, ex: numba entirely from code as it isn't being utilized for cleanup, small QOL changes
Closes issue #1058
> Issue 1058: Fixing variable star errors and filter query for VSP

- exotic/exotic.py
Although it exists within the final fit ([here](https://github.com/rzellem/EXOTIC/blob/main/exotic/exotic.py#L2347-L2354)), I also added it within `fit_lightcurve()` when finding the optimal aperture/annulus size. Let me know if this change is necessary. 
Closes issue #949 nonetheless.
> Issue 949: Mid-Transit Uncertainty limited by Orbital Period

- exotic/exotic_gui.py
- exotic/inputs.py
- inits.json
Due to missing brackets, commas, possible additional symbols, etc., the JSON file would error when attempting to open. These changes should prevent that from happening in the future (hopefully) using regex. Some examples:
"[424 286" --> [424, 286]
"[[465      183], [512     263], [ , [], [], [], [],  []" --> [[465, 183], [512, 263]]
Closes issue #1017
> Issue 1017: Making list of comp stars entries more lenient

- exotic/exotic.py
- exotic/exotic_gui.py
- exotic/output_files.py
- exotic/plots.py
Previously, the code saved time in BJD instead of AAVSO's standard for JD. Converted it to JD instead. 
**Please** review the changes carefully, I heavily modified the functions dealing with time and even flux (just for organization). Trying to document each function in a standard format so that we can get an idea of what each does. 
Closes issue #1068
> Issue 1068: Saving dates in JD for Stellar Variability

- exotic/exotic.py
- exotic/output_files.py
Adding md5 checksum for Exoplanet Watch obs id to AAVSO output file.
Will be outputted as:
`#EPW_MD5-XC={"epw_obs_id": "12fbc1842a22b90f29aab56d267dfd80"}`
Closes #1065
> Issue 1065: md5 checksum

- exotic/inputs.py
Fixes issue where EXOTIC only checks the first header file within `inputs.py` for lat/long/elev.
> Issue 1113: Indexing between header files

- exotic/exotic.py
- exotic/inputs.py
The model fitting code, which makes appropriate use of 'Monte Carlo' techniques when producing solutions, has one problem (which can be a concern for both testing and for research purposes): the random number generator is not seeded in a controlled fashion, which results in the pseudorandom number sequence used being inconsistent from run to run, even for unchanged data and code. On data sets I've worked with, this does tend to result in minor (but not insignificant) changes from run to run.
Tapping into techniques I've seen on other data processing systems, the most simple solution to this is to have the seed for the random number generator be either explicitly controlled, or deterministically generated from the some consistent elements of the source data. To this end, this PR adds a …
> Make random seed settable to make model solving run-to-run consistent

- .gitignore
- exotic/exotic.py
This PR attempts to deal with some issues that can occur in less-than-ideal data sets. Specifically,
Cases where a frame fails to solve properly
Cases where a frame solves properly, but turns out to have the centroid of the target correspond to an 'out of frame' location (that is, failure to have solvable centroid)
Cases where a companion star turns out to be out of frame, resulting in centroid being unsolvable
In all cases, the main goal is to assure that the various generated per-frame data correctly have their per-frame indexes properly adjusted - since there are extensive assumptions that the per-frame index arrays are logically consistent, and of consistent length. Specifically,
aper_data[X][i], where [i] is frame index
psf_data[X][i], where [i] is frame index
airmass[i], where [i] …
> Handle dropped/bad frames cleanly

- run_exotic_linux.sh
This is a check and fallback to handle the fact that, oddly, Ubuntu installations do not put the ~/.local/bin directory (where command_scripts get built and installed, by default) on the PATH - more correctly, if you are running a non-login terminal on Ubuntu (e.g. a terminal window on a graphical shell login), it is not on the path; but if a bash is used for a login shell (e.g. ssh into the system), it is (because it is added by .profile, which is only used for login shells...).
In any case, this uses the bash built-in command, hash, to check if exotic-gui is on the path (nominal path), and runs as before if that is true; else, it checks for existence of the command in ~/.local/bin and runs it from there, if so.
> Fix ./run_exotic_linux.sh to handle Ubuntu not putting ~/.local/bin on PATH

- exotic/exotic.py
The current corruption_check has a problem, due to the hdu1 being an undefined object when an exception is thrown, which results in an exception during the finally path (getattr cannot be called on an undefined object)).
The change switches to 'best practices' for a file like object, using a 'with' to bound the open and cause the close/cleanup to be automatically completed, consisten with fits.open guidance here - https://docs.astropy.org/en/stable/io/fits/index.html
> Shift to 'with' for file - avoid error in finally path when bad

- exotic/exotic.py
Very simple change - just to identify that each AAVSO contributed comparison star, both to indicate that it did happen and what pixel coordinate it corresponds to.
> Add logging of AAVSO comparison star additions

- exotic/exotic.py
This is a simple fix for what is probably a rare scenario, but it should avoid a serious problem when it does occur: when the fix_centroid check on the first frames throws an error or otherwise does not match, and the bad frames are skipped, the pruning of the inputfiles array is done, but the already existing times and jd_times array does not have the corresponding pruning done - this would cause an off by N problem for all downstream processing, as well as the arrays not being of matching lengths during model processing and the like.
I've also added a log message for when this pruning does occur
> Handle times, jd_times arrays properly when first image files skipped

- exotic/exotic.py
This is handling two conditions exposed by Andrew Serine's data (ref - https://uol-ets.slack.com/archives/CJJRP4QKV/p1685032317200029)
EXOTIC does not handle the EXP header as a possible exposure time source
For large fields of view, the AAVSO VSP API pops, due to the API not accepting requests for magnitudes about 12 if the FOV is beyond 180 arcmin
This change consolidates the exposure time parsing into a common routine, and shifts both places where these data are used to call this common parser. It adds EXP as the 3rd preferred header, and returns a 0.0 exposure time in the event of no valid headers (not sure about this last part - it should be 'good enough' for frame time, in general, but not sure otherwise - particularly relative to AAVSO output).
> Add handling of EXP header, and avoid AAVSO error for large fields

- exotic/api/nea.py
Since "or" is a short-circuit operator (https://docs.python.org/3.9/library/stdtypes.html#boolean-operations-and-or-not), the condition can be simplified to avoid code duplication.
> Avoid code duplication

- .gitignore
- exotic/exotic.py
- exotic/output_files.py
- exotic/plate_status.py
This is intended to both act as a usability improvement (making the errors presented to the users for various frame related problems more oriented around what they need to know, versus a more programmer-centric error), and an improvement in the final processing artifacts for the run (specifically, the creation of a PlateStatus-<target>-<date>.csv file recording the various error/warning conditions for each science frame provided by the user - including those rejected due to FITS formatting, inability to be aligned versus the first plate, low flux, and out of frame conditions for the target and each comparison star).
Specifically, existing log messages were switched to log.debug (so they are there for programmer debug, but don't show in the user's console), while more friendly warning …
> Add plate status logging, more friendly (less redundant) errors

- exotic/exotic.py
I believe this is behind some of the errors we've seen, relative to funky plots (with multiple lines) as well as exceptions on plot_flux calls (due to inconsistent array sizes/layouts).
Specifically, this is driven by fit_lightcurve, which can prune the provided times and flux values based on sigma clipping:
https://github.com/rzellem/EXOTIC/blob/develop/exotic/exotic.py#L1449
When this happens, the times and flux arrays used for the light curve can be reduced below the input population - these reduced versions are returned in myfit and as cFlux1 and tFlux1, respectively. When no points are sigma clipped, these are the same as those input to the call (which is why things work most of the time).
The use of the UNPRUNED values later (such as …
> Handle tFlux, cFlux sigma clipping during model matches

- exotic/exotic.py
I'm interested in feedback here, but let me outline the theory and motive:  the existing logic for producing the 'times' versus 'jd_times' arrays for the frame times currently results in jd_times always being a Julian Date, while 'times' will be either a BJD-TDB OR a JD time (depending upon whether the FITS files happen to have or not have BJD headers).  Besides the concern of having those values be essentially of inconsistent definition, the result of this is that the times used in the model fits are (potentially) inconsistent with the time reference for the priors - specifically, the fit_lightcurve (https://github.com/rzellem/EXOTIC/blob/develop/exotic/exotic.py#L1442) is called before the existing code ultimately 'normalizes' the times to BJD-TDB …
> Make times BJD-TDB immediately, remove later conversion

- exotic/exotic.py
- exotic/exotic_gui.py
- exotic/inputs.py
- inits.json
- requirements.txt
This PR adds two new optional settings to inits.json:
- "Demosaic format" (dictionary symbol demosaic_fmt) - if defined and non-null, this specifies the Bayer pattern of the images in the FITS files.  Valid values include 'RGGB', 'BGGR', 'GRBG', 'GBRG'.  RGGB is likely most common pattern for color imagers.  Demosaicing is done using a bilinear interpolation - I opted for this, not because it is the best method, but because I suspected that its simple linear interpolation was less likely to result in added luminocity 'noise' from things like edge detection that visually superior methods use.
- "Demosaic output" (dictionary symbol demosaic_out) - this specifies the disposition of the demosaiced data, since we don't leverage having 3 primaries.   Values include the following:
- [ weightR, …
> Add support for demosaic, for sake of color scopes/cameras (e.g. Unistellar)

- exotic/exotic.py
the sigma_clip function can result in an exception when applying the savgol_filter when the data being processed includes NaNs (as it can when comparison stars drift out of field or are obstructed.
The existing code tests to avoid using the savgol_filter inappropriately (when the array of data is too small), but the test fails to account for the fact that the NaNs are stripped from the array before being used: specifically, it checks for len(ogdata) being greater that or equal to the window_length to be used, but then uses ogdata[~nanmask] as the data to be processed - since [~nanmask] will shrink the array length if any of the fields were NaNs, this makes the previous len(ogdata) test inadequate.  This change simply adjusts the constraint test to be consistent with the data as passed to …
> Prevent exception in sigma clip when data includes NaNs

- exotic/api/filters.py
- exotic/api/ld.py
- exotic/exotic.py
Closes #1210 
- Remove redundancy in naming by auto-generating some value data
- Modify LimbDarkening OOP design to utilize static methods and create appropriate class variables
- Create matcher map to match against punctuation free and spacing normalized user input variables
- Extend filter matching to algorithmically examine filter inputs step-wise from most- to least-critical
- Add `name` option to input filter
- Modify instance setters to set instance filters from class variables
> Filter logic modifications to extend matching

- exotic/api/filters.py
- exotic/api/ld.py
- exotic/exotic.py
Moved lists of generalized filters to the filter module. Update matching against not formally specified filters to use sets. Some additional cleanup. ...
> Additional filter modifications

- exotic/exotic.py
When removing variable stars, I accidentally coded it to remove a list while iterating from it. I duplicated it to avoid the error. Closes #1229
> Issue 1229: Bug for removing variable stars

- exotic/inputs.py
astropy already supports, so just need to recognize appropriate extensions (.fits.fz, fit.fz).   Used fpack to compress files (wow, it works well!), and confirmed correct behavior.
> Add support for fpack based extensions

- examples/README.md
- examples/tess/candidates/inits_file_maker_for_Candidate.py
This pull request adds a script to create an inits file for candidates. The script prompts the user for a TIC ID, scrapes ExoFop, and provides entry choices to create an inits file that can run in `exotic.py` for a candidate. If all parameters are not available on ExoFop, it calculates them for the user. Observatory info can be entered when prompted while running the script or by opening and editing the created inits file later.
- Added `inits_file_maker_for_Candidate.py` in `examples/tess/candidates/`.
This pull request resolves issue #1265.
> Add candidate inits file maker script, resolves #1265

- exotic/api/elca.py
`print_progressbool` was changed to `print_progress` in `elca.py`
This change is required because dynesty expect that argument name: [](https://dynesty.readthedocs.io/en/stable/api.html#dynesty.sampler.Sampler.run_nested)
> Fix for malformed variable name breaking Dynesty/Windows reductions

- .github/workflows/python-publish.yml
- Limit files to proper wheel and archive.
- Specify job dependencies
- Fix missing slash in publication directory
> Update Trusted Publishing spec to meet requirements

- .github/workflows/python-publish.yml
- Remove experimental support for PEP 740 attestations
> Update Trusted Publishing spec to fix bugs

- exotic/api/nea.py
The existing `_tap_query` method constructs the query URL by manually replacing spaces with plus signs` uri_full = uri_full.replace(' ', '+')` but does not URL-encode the entire query string. 
This means that when querying exoplanets with a plus sign (+) in their names, such as "WD 1856+534 b", the planet will not be found.
We can use `urllib.parse` for URL-encoding the ADQL query.
> Issue 1313: Use urllib.parse.quote for URL-encoding the ADQL query (Part 1)

- .github/workflows/python-publish.yml
- Merge trusted publishing changes to `develop` branch for inclusion with next release
> Normalize branches ahead of 4.2.0 release

- exotic/api/colab.py
I was testing out the colab notebooks earlier and saw that it was prompting AAVSO comp stars from the command line. I also noticed it was an issue asking for the comparison stars to be default per issue #1125. I updated the construct of the file to conform to today's initialization file.
**Please do not release this in v4.2.** Save for 4.3 (next week).
Closes #1125
> Issue 1125: Include AAVSO comparison stars as default during initialization file construction for Colab

- exotic/api/colab.py
- exotic/exotic.py
This PR fix #1336 by constraining the mesh_box within the borders of the image.
In particular this was affecting some datasets where AAVSO comparison stars were relatively near the border, causing the process to be slow and errors like the following: 
`Sky background error for Comparison star #4 for file C:\Users\ivenz\Downloads\exotic_sample_data_error_2024-10-21\2024-10-21\LIGHT\HD 209458_2062.FIT - are you sure there is a star at [915.6, 582.0]?`
Very important, this PR also re-enable AAVSO comparison stars by default in Colab. It was disabled a month ago mainly because of issue #1336
@tamimfatahi @rzellem
> Fix mesh_box extending beyond the border of the frame; Re-enable AAVSO comparison stars to Y in Colab

- exotic/exotic.py
- Conditional to check if calibration files are NoneType first!
> Issue 1358: Resolve application error when calibration files are nonexistent
